import { ICommand } from '../types/Command.js';
import { Logger } from '../services/Logger.js';
import readline from 'readline';
import { promises as fs } from 'fs';
import path from 'path';

export interface InitStepContext {
  projectName?: string;
  template?: string;
  useGit?: boolean;
}

export interface InitStep {
  id: string;
  label: string;
  defaultValue?: string;
  run(context: InitStepContext, value: string): Promise<void>;
}

class ProjectNameStep implements InitStep {
  id = 'project-name';
  label = 'Project name';
  defaultValue = 'my-new-project';

  async run(context: InitStepContext, value: string): Promise<void> {
    const projectName = value || this.defaultValue;
    context.projectName = projectName;
    Logger.success(`Project name set to '${projectName}'`);
  }
}

class TemplateStep implements InitStep {
  id = 'template';
  label = 'Template';
  defaultValue = 'basic';

  async run(context: InitStepContext, value: string): Promise<void> {
    const template = value || this.defaultValue;
    context.template = template;
    Logger.success(`Template selected: '${template}'`);
  }
}

class GitInitStep implements InitStep {
  id = 'git-init';
  label = 'Initialize git repository';
  defaultValue = 'yes';

  async run(context: InitStepContext, value: string): Promise<void> {
    const useGit = value?.toLowerCase() !== 'no';
    context.useGit = useGit;
    if (useGit) {
      Logger.success('Git initialization enabled');
    } else {
      Logger.warn('Git initialization skipped');
    }
  }
}

/**
 * Init Command
 * Interactive project initialization wizard with modular steps
 */
export class InitCommand implements ICommand {
  name = 'init';
  description = 'Initialize a new project with interactive step-by-step selections';

  private steps: InitStep[] = [new ProjectNameStep(), new TemplateStep(), new GitInitStep()];

  registerStep(step: InitStep): void {
    this.steps.push(step);
  }

  async execute(args: string[]): Promise<void> {
    const nonInteractive = args.includes('--yes') || args.includes('-y');
    const context: InitStepContext = {};

    Logger.info('Starting interactive initialization wizard...');

    for (const step of this.steps) {
      const rawAnswer = nonInteractive ? step.defaultValue || '' : await this.askQuestion(`${step.label} (${step.defaultValue}) > `);

      await step.run(context, rawAnswer.trim());
    }

    await this.createProjectStructure(context);
    Logger.success('Initialization complete');
    Logger.info(`Final package settings: ${JSON.stringify(context, null, 2)}`);
  }

  private async createProjectStructure(context: InitStepContext): Promise<void> {
    const projectName = context.projectName || 'my-new-project';
    const projectPath = path.resolve(process.cwd(), projectName);

    try {
      await fs.mkdir(projectPath, { recursive: true });
      Logger.success(`Created project folder: ${projectPath}`);
    } catch (error) {
      Logger.error(`Failed to create project folder: ${String(error)}`);
      throw error;
    }

    const packageJson = {
      name: projectName,
      version: '1.0.0',
      description: `Generated by useful-cli-tool init (${projectName})`,
      main: 'index.js',
      scripts: {
        start: 'node index.js',
        test: 'echo "No tests specified" && exit 0'
      },
      license: 'MIT'
    };

    try {
      await fs.writeFile(path.join(projectPath, 'package.json'), JSON.stringify(packageJson, null, 2));
      Logger.success(`Created package.json in ${projectPath}`);
    } catch (error) {
      Logger.error(`Failed to create package.json: ${String(error)}`);
      throw error;
    }

    if (context.useGit) {
      try {
        await this.executeCommand('git init', projectPath);
        Logger.success('Git repository initialized');
      } catch (error) {
        Logger.warn('Git initialization failed, continue without git');
      }
    }
  }

  private async executeCommand(cmd: string, cwd: string): Promise<void> {
    const { exec } = await import('child_process');
    return new Promise((resolve, reject) => {
      exec(cmd, { cwd }, (error) => {
        if (error) {
          reject(error);
          return;
        }
        resolve();
      });
    });
  }

  private askQuestion(question: string): Promise<string> {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    return new Promise((resolve) => {
      rl.question(question, (answer) => {
        rl.close();
        resolve(answer);
      });
    });
  }
}
